# Don't print a new line at the start of the prompt
add_newline = false

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

# Disable the AWS cloud region in prompt
[aws]
disabled = true

# [time]
# disabled = false
# format = "%T"